services:
    # Web Server Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - ./src:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app
            - db

    #   Database Service
    db:
        image: mysql
        container_name: mysql
        volumes:
            - ./mysql/data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: crowdfunding
            MYSQL_ALLOW_EMPTY_PASSWORD: true

    # Application Service
    app:
        container_name: crowdfunding
        build:
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - ./src:/var/www
        ports:
            - "9000:9000"
        working_dir: /var/www

    #phpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "3400:80"
        depends_on:
            - db
